# Generated by Django 5.1.5 on 2025-02-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestSpecific', '0012_alter_applybloodmodelforspecificuser_donate_request_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applybloodmodelforspecificuser',
            old_name='donate_request',
            new_name='requester',
        ),
        migrations.AlterField(
            model_name='applybloodmodelforspecificuser',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
