# Generated by Django 5.1.5 on 2025-02-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestSpecific', '0020_applybloodmodelforspecificuser_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applybloodmodelforspecificuser',
            options={'ordering': ['created']},
        ),
        migrations.RemoveField(
            model_name='applybloodmodelforspecificuser',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='applybloodmodelforspecificuser',
            name='phone',
        ),
        migrations.AlterField(
            model_name='applybloodmodelforspecificuser',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=10),
        ),
    ]
