# Generated by Django 5.1.5 on 2025-02-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestSpecific', '0021_alter_applybloodmodelforspecificuser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applybloodmodelforspecificuser',
            options={},
        ),
        migrations.AddField(
            model_name='applybloodmodelforspecificuser',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='applybloodmodelforspecificuser',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='applybloodmodelforspecificuser',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Cancelled', 'Cancelled'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=10),
        ),
    ]
