# Generated by Django 5.1.5 on 2025-02-15 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0029_alter_donationrequestmodel_blood_and_more'),
        ('requestSpecific', '0022_alter_applybloodmodelforspecificuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applybloodmodelforspecificuser',
            name='blood_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donate.donationrequestmodel'),
        ),
        migrations.AlterField(
            model_name='applybloodmodelforspecificuser',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
