# Generated by Django 5.1.5 on 2025-02-16 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestForBlood', '0039_alter_requestforbloodmodel_blood_and_more'),
        ('requestSpecific', '0036_alter_applybloodmodelforspecificuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='applybloodmodelforspecificuser',
            name='requestmodel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='requestForBlood.requestforbloodmodel'),
        ),
        migrations.AlterField(
            model_name='applybloodmodelforspecificuser',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted'), ('Cancelled', 'Cancelled')], default='Pending', max_length=10),
        ),
    ]
