# Generated by Django 5.1.5 on 2025-02-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestSpecific', '0037_applybloodmodelforspecificuser_requestmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applybloodmodelforspecificuser',
            name='status',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Accepted', 'Accepted'), ('Cancelled', 'Cancelled'), ('Pending', 'Pending')], default='Pending', max_length=10),
        ),
    ]
