# Generated by Django 5.1.5 on 2025-01-18 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationRequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Rejected', 'Rejected'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Accepted', 'Accepted')], default='Pending', max_length=10)),
                ('blood', models.CharField(choices=[('B+', 'B+'), ('AB-', 'AB-'), ('A-', 'A-'), ('B-', 'B-'), ('O+', 'O+'), ('AB+', 'AB+'), ('A+', 'A+'), ('O-', 'O-')], max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
