# Generated by Django 5.1.5 on 2025-01-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0002_donationrequestmodel_addreess_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequestmodel',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='donationrequestmodel',
            name='blood',
            field=models.CharField(choices=[('B+', 'B+'), ('O-', 'O-'), ('AB-', 'AB-'), ('O+', 'O+'), ('B-', 'B-'), ('AB+', 'AB+'), ('A+', 'A+'), ('A-', 'A-')], max_length=3),
        ),
        migrations.AlterField(
            model_name='donationrequestmodel',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled'), ('Pending', 'Pending')], default='Pending', max_length=10),
        ),
    ]
