# Generated by Django 5.1.5 on 2025-01-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0003_donationrequestmodel_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donationrequestmodel',
            options={'ordering': ['last_donate']},
        ),
        migrations.AddField(
            model_name='donationrequestmodel',
            name='last_donate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donationrequestmodel',
            name='unit',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='donationrequestmodel',
            name='blood',
            field=models.CharField(choices=[('AB+', 'AB+'), ('A+', 'A+'), ('O-', 'O-'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('AB-', 'AB-')], max_length=3),
        ),
        migrations.AlterField(
            model_name='donationrequestmodel',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Cancelled', 'Cancelled'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
