# Generated by Django 5.1.5 on 2025-01-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0004_alter_donationrequestmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationrequestmodel',
            name='blood',
            field=models.CharField(choices=[('O+', 'O+'), ('A-', 'A-'), ('AB+', 'AB+'), ('B+', 'B+'), ('A+', 'A+'), ('O-', 'O-'), ('AB-', 'AB-'), ('B-', 'B-')], max_length=3),
        ),
        migrations.AlterField(
            model_name='donationrequestmodel',
            name='status',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled')], default='Pending', max_length=10),
        ),
    ]
