# Generated by Django 5.1.5 on 2025-02-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0014_alter_donationrequestmodel_blood_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationrequestmodel',
            name='blood',
            field=models.CharField(choices=[('O-', 'O-'), ('A-', 'A-'), ('B-', 'B-'), ('B+', 'B+'), ('O+', 'O+'), ('A+', 'A+'), ('AB-', 'AB-'), ('AB+', 'AB+')], max_length=3),
        ),
        migrations.AlterField(
            model_name='donationrequestmodel',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted'), ('Pending', 'Pending')], default='Pending', max_length=10),
        ),
    ]
