# Generated by Django 5.1.5 on 2025-02-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0015_alter_donationrequestmodel_blood_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donationrequestmodel',
            old_name='addreess',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='donationrequestmodel',
            name='blood',
            field=models.CharField(choices=[('B-', 'B-'), ('AB+', 'AB+'), ('A+', 'A+'), ('B+', 'B+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('A-', 'A-')], max_length=3),
        ),
        migrations.AlterField(
            model_name='donationrequestmodel',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted'), ('Cancelled', 'Cancelled')], default='Pending', max_length=10),
        ),
    ]
