# Generated by Django 5.1.5 on 2025-02-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0022_alter_donationrequestmodel_blood_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationrequestmodel',
            name='blood',
            field=models.CharField(choices=[('A-', 'A-'), ('B-', 'B-'), ('O+', 'O+'), ('B+', 'B+'), ('O-', 'O-'), ('AB-', 'AB-'), ('A+', 'A+'), ('AB+', 'AB+')], max_length=3),
        ),
    ]
