# Generated by Django 5.1.5 on 2025-02-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0037_alter_donationrequestmodel_blood_and_more'),
        ('requestForBlood', '0034_alter_requestforbloodmodel_blood_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequestmodel',
            name='specific_request_model',
            field=models.ManyToManyField(blank=True, null=True, to='requestForBlood.requestforbloodmodel'),
        ),
        migrations.AlterField(
            model_name='donationrequestmodel',
            name='blood',
            field=models.CharField(choices=[('AB-', 'AB-'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('A+', 'A+'), ('AB+', 'AB+'), ('O-', 'O-'), ('O+', 'O+')], max_length=3),
        ),
        migrations.AlterField(
            model_name='donationrequestmodel',
            name='status',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Cancelled', 'Cancelled')], default='Pending', max_length=10),
        ),
    ]
