# Generated by Django 5.1.5 on 2025-02-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0047_alter_donationrequestmodel_blood_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationrequestmodel',
            name='blood',
            field=models.CharField(choices=[('AB+', 'AB+'), ('O-', 'O-'), ('B+', 'B+'), ('AB-', 'AB-'), ('A-', 'A-'), ('A+', 'A+'), ('B-', 'B-'), ('O+', 'O+')], max_length=3),
        ),
        migrations.AlterField(
            model_name='donationrequestmodel',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled'), ('Pending', 'Pending')], default='Pending', max_length=10),
        ),
    ]
