# Generated by Django 5.1.5 on 2025-01-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customusermodel_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='blood_group',
            field=models.CharField(choices=[('O-', 'O-'), ('B-', 'B-'), ('A-', 'A-'), ('B+', 'B+'), ('AB-', 'AB-'), ('AB+', 'AB+'), ('A+', 'A+'), ('O+', 'O+')], max_length=3),
        ),
    ]
