# Generated by Django 5.1.5 on 2025-01-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customusermodel_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='blood_group',
            field=models.CharField(choices=[('AB-', 'AB-'), ('B-', 'B-'), ('O-', 'O-'), ('O+', 'O+'), ('A-', 'A-'), ('B+', 'B+'), ('AB+', 'AB+'), ('A+', 'A+')], max_length=3),
        ),
    ]
