# Generated by Django 5.1.5 on 2025-01-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customusermodel_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='blood_group',
            field=models.CharField(choices=[('O+', 'O+'), ('A-', 'A-'), ('B-', 'B-'), ('A+', 'A+'), ('AB+', 'AB+'), ('B+', 'B+'), ('AB-', 'AB-'), ('O-', 'O-')], max_length=3),
        ),
    ]
