# Generated by Django 5.1.5 on 2025-01-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customusermodel_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='confirm_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='blood_group',
            field=models.CharField(choices=[('B+', 'B+'), ('O-', 'O-'), ('O+', 'O+'), ('AB-', 'AB-'), ('A+', 'A+'), ('B-', 'B-'), ('A-', 'A-'), ('AB+', 'AB+')], max_length=3),
        ),
    ]
