# Generated by Django 5.1.5 on 2025-01-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customusermodel_confirm_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusermodel',
            name='confirm_password',
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='blood_group',
            field=models.CharField(choices=[('B+', 'B+'), ('O-', 'O-'), ('O+', 'O+'), ('AB+', 'AB+'), ('A-', 'A-'), ('AB-', 'AB-'), ('B-', 'B-'), ('A+', 'A+')], max_length=3),
        ),
    ]
