# Generated by Django 5.1.5 on 2025-01-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_customusermodel_confirm_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='blood_group',
            field=models.CharField(choices=[('AB+', 'AB+'), ('AB-', 'AB-'), ('B+', 'B+'), ('O-', 'O-'), ('A-', 'A-'), ('A+', 'A+'), ('B-', 'B-'), ('O+', 'O+')], max_length=3),
        ),
    ]
