# Generated by Django 5.1.5 on 2025-02-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customusermodel_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('B+', 'B+'), ('O-', 'O-'), ('B-', 'B-'), ('A-', 'A-')], max_length=3),
        ),
    ]
