# Generated by Django 5.1.5 on 2025-02-11 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_customusermodel_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='blood_group',
            field=models.CharField(choices=[('B-', 'B-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('AB-', 'AB-'), ('O-', 'O-'), ('O+', 'O+'), ('AB+', 'AB+')], max_length=3),
        ),
    ]
