# Generated by Django 5.1.5 on 2025-02-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_customusermodel_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='blood_group',
            field=models.CharField(choices=[('O-', 'O-'), ('AB+', 'AB+'), ('A+', 'A+'), ('A-', 'A-'), ('AB-', 'AB-'), ('B-', 'B-'), ('B+', 'B+'), ('O+', 'O+')], max_length=3),
        ),
    ]
