# Generated by Django 5.1.5 on 2025-02-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_customusermodel_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='blood_group',
            field=models.CharField(choices=[('B-', 'B-'), ('A-', 'A-'), ('B+', 'B+'), ('O+', 'O+'), ('O-', 'O-'), ('AB-', 'AB-'), ('A+', 'A+'), ('AB+', 'AB+')], max_length=3),
        ),
    ]
