# Generated by Django 5.1.5 on 2025-02-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_customusermodel_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='blood_group',
            field=models.CharField(choices=[('O-', 'O-'), ('O+', 'O+'), ('AB+', 'AB+'), ('A+', 'A+'), ('A-', 'A-'), ('B-', 'B-'), ('AB-', 'AB-'), ('B+', 'B+')], max_length=3),
        ),
    ]
