# Generated by Django 5.1.5 on 2025-02-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_alter_customusermodel_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='blood_group',
            field=models.CharField(choices=[('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('A+', 'A+'), ('O+', 'O+'), ('AB-', 'AB-'), ('O-', 'O-'), ('AB+', 'AB+')], max_length=3),
        ),
    ]
