# Generated by Django 5.1.5 on 2025-02-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_alter_customusermodel_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('AB-', 'AB-'), ('B+', 'B+'), ('A-', 'A-'), ('AB+', 'AB+'), ('O-', 'O-'), ('B-', 'B-'), ('O+', 'O+')], max_length=3),
        ),
    ]
