# Generated by Django 5.1.5 on 2025-02-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_alter_customusermodel_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('O+', 'O+'), ('B-', 'B-'), ('AB-', 'AB-'), ('O-', 'O-'), ('AB+', 'AB+'), ('B+', 'B+')], max_length=3),
        ),
    ]
