# Generated by Django 5.1.5 on 2025-02-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_alter_customusermodel_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='blood_group',
            field=models.CharField(choices=[('AB-', 'AB-'), ('B+', 'B+'), ('AB+', 'AB+'), ('B-', 'B-'), ('O+', 'O+'), ('A+', 'A+'), ('A-', 'A-'), ('O-', 'O-')], max_length=3),
        ),
    ]
