# Generated by Django 5.1.5 on 2025-02-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_alter_customusermodel_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='blood_group',
            field=models.CharField(choices=[('O-', 'O-'), ('AB+', 'AB+'), ('A+', 'A+'), ('B+', 'B+'), ('B-', 'B-'), ('AB-', 'AB-'), ('A-', 'A-'), ('O+', 'O+')], max_length=3),
        ),
    ]
