# Generated by Django 5.1.5 on 2025-01-18 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestForBloodModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Rejected', 'Rejected'), ('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled')], default='Pending', max_length=10)),
                ('blood', models.CharField(choices=[('O+', 'O+'), ('A-', 'A-'), ('AB+', 'AB+'), ('B+', 'B+'), ('A+', 'A+'), ('O-', 'O-'), ('AB-', 'AB-'), ('B-', 'B-')], max_length=3)),
                ('addreess', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=100)),
                ('unit', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
