# Generated by Django 5.1.5 on 2025-01-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestForBlood', '0003_alter_requestforbloodmodel_blood_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestforbloodmodel',
            name='blood',
            field=models.CharField(choices=[('A+', 'A+'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('A-', 'A-'), ('O+', 'O+'), ('B-', 'B-'), ('B+', 'B+'), ('O-', 'O-')], max_length=3),
        ),
        migrations.AlterField(
            model_name='requestforbloodmodel',
            name='status',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Cancelled', 'Cancelled'), ('Pending', 'Pending'), ('Accepted', 'Accepted')], default='Pending', max_length=10),
        ),
    ]
