# Generated by Django 5.1.5 on 2025-02-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestForBlood', '0010_alter_requestforbloodmodel_blood_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestforbloodmodel',
            old_name='addreess',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='requestforbloodmodel',
            name='blood',
            field=models.CharField(choices=[('O-', 'O-'), ('A-', 'A-'), ('B-', 'B-'), ('B+', 'B+'), ('O+', 'O+'), ('A+', 'A+'), ('AB-', 'AB-'), ('AB+', 'AB+')], max_length=3),
        ),
        migrations.AlterField(
            model_name='requestforbloodmodel',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted'), ('Pending', 'Pending')], default='Pending', max_length=10),
        ),
    ]
