# Generated by Django 5.1.5 on 2025-02-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestForBlood', '0012_alter_requestforbloodmodel_blood_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestforbloodmodel',
            name='blood',
            field=models.CharField(choices=[('O+', 'O+'), ('A+', 'A+'), ('O-', 'O-'), ('B+', 'B+'), ('B-', 'B-'), ('AB-', 'AB-'), ('AB+', 'AB+'), ('A-', 'A-')], max_length=3),
        ),
        migrations.AlterField(
            model_name='requestforbloodmodel',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=10),
        ),
    ]
