# Generated by Django 5.1.5 on 2025-02-11 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestForBlood', '0015_alter_requestforbloodmodel_blood_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestforbloodmodel',
            name='blood',
            field=models.CharField(choices=[('B-', 'B-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('AB-', 'AB-'), ('O-', 'O-'), ('O+', 'O+'), ('AB+', 'AB+')], max_length=3),
        ),
        migrations.AlterField(
            model_name='requestforbloodmodel',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled')], default='Pending', max_length=10),
        ),
    ]
