# Generated by Django 5.1.5 on 2025-02-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestForBlood', '0019_alter_requestforbloodmodel_blood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestforbloodmodel',
            name='blood',
            field=models.CharField(choices=[('B+', 'B+'), ('A+', 'A+'), ('AB+', 'AB+'), ('B-', 'B-'), ('A-', 'A-'), ('O-', 'O-'), ('AB-', 'AB-'), ('O+', 'O+')], max_length=3),
        ),
        migrations.AlterField(
            model_name='requestforbloodmodel',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')], default='Pending', max_length=10),
        ),
    ]
