# Generated by Django 5.1.5 on 2025-02-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestForBlood', '0026_alter_requestforbloodmodel_blood_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestforbloodmodel',
            name='blood',
            field=models.CharField(choices=[('A+', 'A+'), ('O+', 'O+'), ('O-', 'O-'), ('B-', 'B-'), ('AB+', 'AB+'), ('B+', 'B+'), ('A-', 'A-'), ('AB-', 'AB-')], max_length=3),
        ),
        migrations.AlterField(
            model_name='requestforbloodmodel',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled'), ('Accepted', 'Accepted')], default='Pending', max_length=10),
        ),
    ]
