# Generated by Django 5.1.5 on 2025-02-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestForBlood', '0039_alter_requestforbloodmodel_blood_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestforbloodmodel',
            name='blood',
            field=models.CharField(choices=[('A-', 'A-'), ('AB+', 'AB+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('AB-', 'AB-'), ('B+', 'B+')], max_length=3),
        ),
        migrations.AlterField(
            model_name='requestforbloodmodel',
            name='status',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Accepted', 'Accepted'), ('Cancelled', 'Cancelled'), ('Pending', 'Pending')], default='Pending', max_length=10),
        ),
    ]
